### PR TITLE
Performance tweak in toolAggregate

### PR DESCRIPTION
**Pull request by tscheypidi**
Making use of the Matrix package toolAggregate is now significantly faster in various situations

### CODE REVIEW

**Comment by giannou** [comment]
Nice! Has this been tested with both fullYXZ functions?

**Comment by tscheypidi** [comment]
has been tested with fullValidation and fullMAgPIE

**Comment by giannou** [comment]
Should we run a test with fullREMIND also?

**Comment by tscheypidi** [comment]
from my perspective this is not needed as there is quite some overlap between the tested setup and fullREMIND...in addition toolAggregate comes which a rather good suite of tests which covered all emerging problems

**Comment by giannou** [comment]
> from my perspective this is not needed as there is quite some overlap between the tested setup and fullREMIND...in addition toolAggregate comes which a rather good suite of tests which covered all emerging problems

fair enough

**Review by giannou — APPROVED** [review]

**Pull request merged**
